[package]
name = "torvo"
description = "Elegant pure functional programming language"
authors = ["Felipe Nascimento <felipenasgomes@gmail.com>"]
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = { version = "4.4.18", features = ["derive"] }
protobuf = "3.3.0"

[build-dependencies]
protobuf-codegen = "3.3.0"
